name: Bivium
favicon: null
layout_spectrum: 0.2984912060201168
typography_spectrum: 0.19857777724973857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41802205378189683
  lightness: 0.43481420166790485
  saturation: 0.20222546276636422
  rhythmicContrast: 0.3737548787612468
purpose: []
